server:
  port: 8881
  servlet:
    context-path: /minos
    session:
      timeout: 2H
spring:
  main:
    banner-mode: off
  application:
    name: minos
  session:
    redis:
      namespace: spring:session
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      password: '!@Wasd135139'
      lettuce:
        pool:
          enabled: true
          max-idle: 8
          min-idle: 8
  datasource:
    url: jdbc:mysql://localhost:3306
    hikari:
      catalog: minos
      username: root
      password: '!@Wasd135139'
      # 初始化连接时,测试连接sql
      connection-init-sql: select 1
      # 连接测试sql
      connection-test-query: select 1
      # 最小闲置连接数
      minimum-idle: 8
      # 最多连接数
      maximum-pool-size: 24
      # 长连接时长
      keepalive-time: 10000
      data-source-properties:
        useUnicode: true
        characterEncoding: UTF-8
        useSSL: false
        # 东八区
        serverTimezone: GMT+8
        allowMultiQueries: true
        # 自动重连
        autoReconnect: true
business:
  tree:
    menu:
      length: 4
      digits: 0123456789abcdefghijklmnopqrstuvwxyz
      maximum-depth: 10
  exception:
    response-real-exceptions: true
  security:
    permit-all:
      - path: /v3/api-docs/**
      - path: /system/setting/**
logging:
  level:
    com.pep: debug
    root: info
    org.springframework.transaction: DEBUG
# springdoc-openapi项目配置
springdoc:
  group-configs:
    - group: 'default'
      display-name: '默认分组'
      paths-to-match: '/**'
      packages-to-scan: com.pep.minos
# knife4j的增强配置, 不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-open-api: on
    enable-footer: false
    enable-footer-custom: true
    footer-custom-content: 'Copyright © 2026-2027 Minos. All Rights Reserved.'
