spring:
  main:
    banner-mode: off
  application:
    name: minos
server:
  port: 8881
  servlet:
    context-path: /minos

business:
  exception:
    response-real-exceptions: false

# springdoc-openapi项目配置
springdoc:
  group-configs:
    - group: 'default'
      display-name: '默认分组'
      paths-to-match: '/**'
      packages-to-scan: com.pep.minos
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-open-api: on
    enable-footer: false
    enable-footer-custom: true
    footer-custom-content: 'Copyright © 2025-2026 Minos. All Rights Reserved.'
